# MinMaxScaler calculations

- By hand: X_train
    - [[1 1]
    -  [2 4]
    -  [-2 2]] 
- Answer: X_train
    - [[0.75 0]
    - [1 1]
    - [0 0.33]]

- By hand: X_test
    - [[1 2]
    - [2 2]]
- Answer: X_test: 
    - [[0.75 0.33]
    - [1 0.33]]

In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
array_train = np.array([1,1,2,4,-2,2])
matrix_train = np.matrix(array_train).reshape([3,2])
scaler = MinMaxScaler()
scaled_matrix_train = scaler.fit_transform(matrix_train)
print(scaled_matrix_train)

array_test = np.array([1,2,2,2])
matrix_test = np.matrix(array_test).reshape(2,2)
scaled_matrix_test = scaler.transform(matrix_test)
print(scaled_matrix_test)

[[0.75       0.        ]
 [1.         1.        ]
 [0.         0.33333333]]
[[0.75       0.33333333]
 [1.         0.33333333]]


C:\Users\FabianAndersson-AIU2\.virtualenvs\Machinelearning-Fabian-Andersson-w7oPBvBJ\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\FabianAndersson-AIU2\.virtualenvs\Machinelearning-Fabian-Andersson-w7oPBvBJ\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\FabianAndersson-AIU2\.virtualenvs\Machinelearning-Fabian-Andersson-w7oPBvBJ\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please conver

In [11]:
array_train = np.asarray([1, 8, 7, 2, 3, 4]).reshape([3,2])
print(array_train)
scaler = MinMaxScaler()
scaled_matrix_train = scaler.fit_transform(array_train)
print(scaled_matrix_train)

array_test = np.asarray([5,9,6,2]).reshape([2,2])
print(array_test)
scaled_matrix_test = scaler.transform(array_test)
print(scaled_matrix_test)

[[1 8]
 [7 2]
 [3 4]]
[[0.         1.        ]
 [1.         0.        ]
 [0.33333333 0.33333333]]
[[5 9]
 [6 2]]
[[0.66666667 1.16666667]
 [0.83333333 0.        ]]
