# Exercises for gradiant descent

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib as plt

In [14]:
np.random.seed(42)
array_index = 0
samples = 1000
X = np.random.rand(samples, 2)
intercept = np.ones(samples)

epsilon = np.random.randn(samples)

for i in x:
    y = 3*x[array_index][0] + 5*x[array_index][1] + 3 + epsilon
    array_index +=1 

y = y.reshape(-1,1)
x = np.c_[intercept, X]

print(x)

[[1.         0.37454012 0.95071431]
 [1.         0.73199394 0.59865848]
 [1.         0.15601864 0.15599452]
 ...
 [1.         0.75137509 0.65695516]
 [1.         0.95661462 0.06895802]
 [1.         0.05705472 0.28218707]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
def gradient_desecent(X, y, learning_rate=0.1, epochs=500):
    m = len(X)

    theta = np.random.randn(X.shape[1], 1)
    print(theta.shape)

    for _ in range(epochs):
        gradient = 2 / m * X.T @ (X @ theta - y)
        theta -= learning_rate*gradient
    
    return theta

theta = gradient_desecent(x, y)
print(len(theta))
print(theta)

(3, 1)
3
[[ 4.6912974 ]
 [-0.03691741]
 [-0.15449943]]
